### ISSUE TITLE
Trouble connecting with msal 

### ISSUE THREAD

**Issue by medelmetoui** [YesWeCandrew/PyConnectDataverse#2]
Hey i registred my app in entra ID
I got my power apps env url

i made all the steps but when i run pcd_test_connection.py i got prompted to a authentication web page indicating :

AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope offline_access openid profile {NAME}crm4.dynamics.com/user_impersonation is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

Thanks in advance

**Comment by YesWeCandrew** [comment]
Hi @medelmetoui sorry you’re having problems - It’s hard to say with just this information, but I think that maybe the environmentURI in your ENV JSON is wrong?

Does the format match the format as provided in the [example-env.json](https://github.com/YesWeCandrew/PyConnectDataverse/blob/master/example-env.json)? It should start https:// and end with a /.

Hope this helps!

**Comment by medelmetoui** [comment]
Thanks a lot that was it !
This repo looks promising by the way, thank you,
I'm now trying to get the dataverse data

**Comment by YesWeCandrew** [comment]
Nice! Glad that solved it - will close the issue for now. Hope the repo gets you what you need!
