### ISSUE TITLE
Downloading a file from a Dataverse table

### ISSUE THREAD

**Issue by Luggi11** [YesWeCandrew/PyConnectDataverse#3]
Hey, I use your code to query simple information from my Dataverse tables and summarize it in an HTML. Now I have the problem that I have a file column in my table and I try to download it in vain. Do you have any idea how this could work?

Thank you for sharing your work with everyone and thanks in advance :)

**Comment by YesWeCandrew** [comment]
Hey @Luggi11 looks like you found a resolution, mind sharing how you did it in case anyone else wants to do the same thing?
